name: Application deploy

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      test_only:
        required: false
        type: string
        default: "false"
        
    secrets:
      deploy_host:
        required: true

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - uses: anna-money/workflow-deploy/.github/actions/deploy-production@master
        with:
          service_name: ${{ inputs.name }}
          service_version: ${{ inputs.version }}
          test_only: ${{ inputs.test_only }}
          deploy_host: ${{ secrets.deploy_host }}
